Fix the other pipelines issue, Create a new one (#80)
* Fix the other pipelines issue

Create a new one

```
make py.sdist.public-api && ( cd dist/ && tar -xzvf qdrant_cloud_public_api-0.0.0.tar.gz )
rm -rf dist
```

In cluster-api
```
$ uv add ../public-api/dist/qdrant_cloud_public_api-0.0.0.tar.gz
$ make test

.venv/bin/ruff format cluster_api smoke_tests tests public_api
989 files left unchanged
.venv/bin/ruff check --fix cluster_api smoke_tests tests public_api
All checks passed!
./libexec/wrong_imports.sh
.venv/bin/ruff check cluster_api smoke_tests tests public_api
All checks passed!
PYTEST_TIMEOUT=20 uv run -m pytest tests
================================================= test session starts ==================================================
platform darwin -- Python 3.12.10, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/a/p/qdrant/cloud/api
configfile: pyproject.toml
plugins: cov-5.0.0, freezegun-0.4.2, asyncio-0.25.3, xdoctest-1.2.0, typeguard-4.3.0, timeout-2.3.1, mock-3.14.0, anyio-4.6.2.post1
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=function
timeout: 20.0s
timeout method: signal
timeout func_only: False
collected 2126 items / 1 error

======================================================== ERRORS ========================================================
__________________________________________ ERROR collecting tests/public_api ___________________________________________
Traceback (most recent call last):
  File "/Users/a/p/qdrant/cloud/api/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 710, in _importconftest
    mod = import_path(
          ^^^^^^^^^^^^
  File "/Users/a/p/qdrant/cloud/api/.venv/lib/python3.12/site-packages/_pytest/pathlib.py", line 582, in import_path
    importlib.import_module(module_name)
  File "/opt/homebrew/Cellar/python@3.12/3.12.10/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/Users/a/p/qdrant/cloud/api/.venv/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 184, in exec_module
    exec(co, module.__dict__)
  File "/Users/a/p/qdrant/cloud/api/tests/public_api/conftest.py", line 4, in <module>
    from public_api.grpc_server import QCGrpcServer
  File "/Users/a/p/qdrant/cloud/api/public_api/grpc_server.py", line 10, in <module>
    from qdrant.cloud.booking.v1 import booking_pb2, booking_pb2_grpc
ModuleNotFoundError: No module named 'qdrant.cloud.booking'
=============================================== short test summary info ================================================
ERROR tests/public_api - ModuleNotFoundError: No module named 'qdrant.cloud.booking'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================== 1 error in 1.19s ===================================================
```

* Fix sdist creation.

* Working version

# Conflicts:
#	pyproject.toml

---------

Co-authored-by: Mikheil Lomidze <mikheil.lomidze@qdrant.com>